### ISSUE TITLE
Feature: User can view the cards from a set.

### ISSUE THREAD

**Issue by tomxnguy** [tomxnguy/MTG-Standard#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the cards from a set.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user clicks on the name of a set, a grid of cards will show.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Front Page Standard Sets]<img src="https://github.com/tomxnguy/ajax-project/assets/124644438/e8701cd5-cd3f-4e25-94c6-4c7853512799" width="200">
![Set View]<img src="https://github.com/tomxnguy/ajax-project/assets/124644438/aca75780-9c41-4642-a0e5-8af5796269a2" width="200">
![Front Page Desk Top View]<img src="https://github.com/tomxnguy/ajax-project/assets/124644438/e97b1792-6051-4e0a-b2a4-806cf83cf404" width="400">
![Set Desktop View]<img src="https://github.com/tomxnguy/ajax-project/assets/124644438/1100f9f7-1c51-4062-9c37-05653dfa7f03" width="400">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML for the header that matches the figma. 
- [x] Below header, implement 'sets available view' of all sets that are available.
   - [x] 8 `<a>’ tags corresponding to the sets that will be viewed.
   - [x] Implement a button that will lead to 'deck build view' the deck that the user is building. 
- [x] Create a 'cards view' page that will be hidden:
   - [x] Create a setName banner beneath containing an empty string for the title. 
   - [x] 100 spaces for each card image (4 columns x 25 rows)
      - [x] Add placeholder image. (Back of MTG cards) 
   - [x] Shows a `'button'` on top left of page that will lead back to 'sets available view'.
   - [x] Create 5 buttons corresponding to the color that is to be filtered (W U B R G)
- [x] Create a `'data.js'` file that will use XMLHttpRequest to request data from 'https://docs.magicthegathering.io/':
- [x] Create dummy cards and create a DOM for the cards that are going to be displayed in set view. 
- [x] Add `'click'` event listener that : 
   - [x] Listens to the click of one of the anchor tags of one of the sets in 'sets available view'. 
   - [x] Swaps to 'cards view'.
   - [x] Changes the title of the setName banner with the setName that was clicked on. 
   - [x] Changes the src attribute of each space to with the `'values'` from imageURL `'key'` from XMLHttpRequest. 

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
