### ISSUE TITLE
Feature: User can click on a color and filter cards that are of that color.

### ISSUE THREAD

**Issue by tomxnguy** [tomxnguy/MTG-Standard#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on a color and filter cards that are of that color.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will see 5 buttons near the top of the page while looking at the set that they chose. When deciding the color, the card grid will change to cards that are of that color type.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img src="https://github.com/tomxnguy/MTG-Standard/assets/124644438/d9c2196b-d7b6-4ead-a055-538d7bb7e99e" width="200">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create event listeners that listen for a 'color radio' button to be clicked. 
   - [x] When a color radio button is checked, the URL for the API is changed to filter out cards of that color from that specific deck.
- [x]  Write a function that can be reused for card views of each set. 

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
